### ISSUE TITLE
second pull is the same as first one

### ISSUE THREAD

**Issue by igorpecovnik** [SufferMyJoy/dobsondev-shortcodes#2]
Latest version 1.1.9 is broken on reading Github files. I use few files but it always show one.

Keep the good job!

**Comment by dobsondev** [comment]
Can I get a URL to the page and also the shortcodes your using please? Also do you know if it worked before version 1.1.9?

**Comment by igorpecovnik** [comment]
Yes, it is working fine with 1.1.8. Wordpress is latest and I went back to 1.1.8 to maintain functionality.

This page with 1.1.9
http://www.armbian.com/documentation/
Content:
[embedGitHubContent owner="igorpecovnik" repo="lib" path="documentation/user-faq.md" markdown="Yes"]
[embedGitHubContent owner="igorpecovnik" repo="lib" path="documentation/geek-faq.md" markdown="Yes"]

had the same content as:

http://www.armbian.com/github/
Content:
[embedGitHubReadme owner="igorpecovnik" repo="lib" cache_id="id2"]

**Comment by dobsondev** [comment]
Hey Igor, It's fixed now.

When moving from version 1.1.8 to 1.1.9 the GitHub File Contents Shortcode API call got switched to the same one as the README file instead of the file one so that's why the error was happening. The new version (1.1.10) has fixed this error. You can see the problem below:

This is what the call was changed to (this is how you get the README file):

``` php
curl_setopt_array($curl, array(
          CURLOPT_RETURNTRANSFER => 1,
          CURLOPT_URL => 'https://api.github.com/repos/' . $owner . '/' . $repo . '/readme',
          CURLOPT_USERAGENT => $repo,
          CURLOPT_HEADER => false,
          CURLOPT_SSL_VERIFYPEER => false
));
```

But it really should have been (and this is what it is now):

``` php
curl_setopt_array($curl, array(
          CURLOPT_RETURNTRANSFER => 1,
          CURLOPT_URL => 'https://api.github.com/repos/' . $owner . '/' . $repo . '/contents/' . $path,
          CURLOPT_USERAGENT => $repo,
          CURLOPT_HEADER => false,
          CURLOPT_SSL_VERIFYPEER => false
));
```

I don't know how that got past me but I'm glad its fixed now. Thanks for letting me know about this error Igor, I really appreciate it!
